/**
 * Generate OpenAPI schema + TS types from a running divdag_server.
 *
 * Usage:
 *   pnpm gen:sdk              # fetch from VITE_SERVER_URL (default http://localhost:8000), regenerate types.gen.ts
 *   pnpm gen:sdk --check      # regenerate to a temp file and fail if it differs from committed types.gen.ts (CI gate)
 *
 * If server is not running, falls back to the committed `web/openapi.json`.
 */

import { writeFileSync, readFileSync, existsSync, mkdtempSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { tmpdir } from 'node:os'
import openapiTS, { astToString } from 'openapi-typescript'

const SERVER_URL = process.env.VITE_SERVER_URL || 'http://localhost:8000'
const OPENAPI_JSON = resolve(import.meta.dirname, '..', 'openapi.json')
const TYPES_GEN = resolve(import.meta.dirname, '..', 'src', 'sdk', 'types.gen.ts')
const SCHEMA_PATH = '/api/v1/schema'

async function fetchSchema(): Promise<string> {
  // Try live server first.
  try {
    const r = await fetch(`${SERVER_URL}${SCHEMA_PATH}`)
    if (r.ok) {
      const text = await r.text()
      // Validate it's JSON
      JSON.parse(text)
      // Persist a snapshot for offline use + audit
      writeFileSync(OPENAPI_JSON, text, 'utf-8')
      return text
    }
  } catch {
    // fall through to file
  }
  if (existsSync(OPENAPI_JSON)) {
    return readFileSync(OPENAPI_JSON, 'utf-8')
  }
  throw new Error(
    `Cannot fetch OpenAPI from ${SERVER_URL}${SCHEMA_PATH} and no committed fallback at ${OPENAPI_JSON}. ` +
      `Start divdag_server first (uv run python -m divdag_server).`,
  )
}

async function generateTypes(schemaJson: string): Promise<string> {
  // openapi-typescript accepts the raw JSON string or a parsed object; pass the
  // string so we get the broadest input compatibility across versions.
  const ast = await openapiTS(schemaJson, {
    exportType: true,
    immutable: true,
    enumValues: false,
  })
  const body = astToString(ast)
  const header = `/** AUTO-GENERATED by \`pnpm gen:sdk\` from web/openapi.json. Do not edit by hand. */\n\n/* eslint-disable */\n/* tslint:disable */\n\n`
  return header + body
}

async function main(): Promise<void> {
  const checkMode = process.argv.includes('--check')
  const schema = await fetchSchema()
  const generated = await generateTypes(schema)

  if (checkMode) {
    const tmpDir = mkdtempSync(join(tmpdir(), 'divdag-sdk-'))
    const tmpFile = join(tmpDir, 'types.gen.ts')
    writeFileSync(tmpFile, generated, 'utf-8')
    const committed = readFileSync(TYPES_GEN, 'utf-8')
    if (committed !== generated) {
      console.error('SDK drift detected: types.gen.ts does not match the OpenAPI schema.')
      console.error('Run `pnpm gen:sdk` to regenerate, then commit the result.')
      process.exit(1)
    }
    console.log('SDK drift check: OK (types.gen.ts matches schema)')
    return
  }

  writeFileSync(TYPES_GEN, generated, 'utf-8')
  console.log(`SDK regenerated: ${TYPES_GEN}`)
  console.log(`Schema snapshot:  ${OPENAPI_JSON}`)
}

main().catch((err: unknown) => {
  console.error('gen:sdk failed:', err instanceof Error ? err.message : String(err))
  process.exit(1)
})
