/** AUTO-GENERATED by `pnpm gen:sdk` from web/openapi.json. Do not edit by hand. */

/* eslint-disable */
/* tslint:disable */

export type paths = {
    readonly "/api/v1/domains": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** ListDomains */
        readonly get: operations["ApiV1DomainsListDomains"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/executors": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** ListExecutors */
        readonly get: operations["ApiV1ExecutorsListExecutors"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/templates": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** ListTemplates */
        readonly get: operations["ApiV1TemplatesListTemplates"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/runs": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** ListRuns */
        readonly get: operations["ApiV1RunsListRuns"];
        readonly put?: never;
        /** CreateRun */
        readonly post: operations["ApiV1RunsCreateRun"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/runs/{run_id}/events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** GetEvents */
        readonly get: operations["ApiV1RunsRunIdEventsGetEvents"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/runs/{run_id}/pipeline": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** GetPipeline */
        readonly get: operations["ApiV1RunsRunIdPipelineGetPipeline"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/runs/{run_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** GetRun */
        readonly get: operations["ApiV1RunsRunIdGetRun"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/nodes/{node_run_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** GetNode */
        readonly get: operations["ApiV1NodesNodeRunIdGetNode"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/nodes/{node_run_id}/attempts": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** ListAttempts */
        readonly get: operations["ApiV1NodesNodeRunIdAttemptsListAttempts"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/runs/{run_id}/items/{item_id}/artifacts/{slot}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** GetItemArtifactBytes */
        readonly get: operations["ApiV1RunsRunIdItemsItemIdArtifactsSlotGetItemArtifactBytes"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/runs/{run_id}/items/{item_id}/artifacts": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** GetItemArtifacts */
        readonly get: operations["ApiV1RunsRunIdItemsItemIdArtifactsGetItemArtifacts"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/runs/{run_id}/state": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** GetStateIndex */
        readonly get: operations["ApiV1RunsRunIdStateGetStateIndex"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/runs/{run_id}/state/object": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** GetStateObject */
        readonly get: operations["ApiV1RunsRunIdStateObjectGetStateObject"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/attempts/{attempt_id}/transcript": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** GetTranscript */
        readonly get: operations["ApiV1AttemptsAttemptIdTranscriptGetTranscript"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/attempts/{attempt_id}/stream": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** StreamAttempt */
        readonly get: operations["ApiV1AttemptsAttemptIdStreamStreamAttempt"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/events/stream": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** StreamGlobal */
        readonly get: operations["ApiV1EventsStreamStreamGlobal"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/runs/{run_id}/events/stream": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** StreamRun */
        readonly get: operations["ApiV1RunsRunIdEventsStreamStreamRun"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/projects/{project_id}/plan": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** GetPlan */
        readonly get: operations["ApiV1ProjectsProjectIdPlanGetPlan"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/projects/{project_id}/ledger": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** ListLedger */
        readonly get: operations["ApiV1ProjectsProjectIdLedgerListLedger"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/projects/{project_id}/ledger/refresh": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** RefreshLedger */
        readonly post: operations["ApiV1ProjectsProjectIdLedgerRefreshRefreshLedger"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/agents/processes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** ListProcesses */
        readonly get: operations["ApiV1AgentsProcessesListProcesses"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/agents/processes/status": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** StatusText */
        readonly get: operations["ApiV1AgentsProcessesStatusStatusText"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/agents/processes/stop-all": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** StopAll */
        readonly post: operations["ApiV1AgentsProcessesStopAllStopAll"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/agents/processes/{key}/stop": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** StopProcess */
        readonly post: operations["ApiV1AgentsProcessesKeyStopStopProcess"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** ArtifactRefOut */
        readonly ArtifactRefOut: {
            readonly key: {
                readonly [key: string]: unknown;
            };
            readonly kind: string;
            readonly path: string;
            readonly sha256: string;
            readonly size: number;
            /** @default  */
            readonly written_at: string;
        };
        /** ArtifactSlotOut */
        readonly ArtifactSlotOut: {
            readonly name: string;
            readonly label: string;
            readonly view: string;
            /** @default  */
            readonly description: string;
            /** @default false */
            readonly optional: boolean;
        };
        /** ArtifactSpecOut */
        readonly ArtifactSpecOut: {
            readonly slots?: readonly components["schemas"]["ArtifactSlotOut"][];
            /** @default tabs */
            readonly default_view: string;
            /** @default  */
            readonly label: string;
        };
        /** AttemptOut */
        readonly AttemptOut: {
            readonly id: string;
            readonly node_run_id: string;
            readonly attempt: number;
            readonly status: string;
            /** @default mock */
            readonly backend: string;
            /** @default  */
            readonly transcript_path_rel: string;
            readonly result?: {
                readonly [key: string]: unknown;
            } | null;
            readonly started_at?: string | null;
            readonly finished_at?: string | null;
        };
        /** DomainOut */
        readonly DomainOut: {
            readonly id: string;
            readonly label: string;
            readonly version: string;
            readonly executors?: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly templates?: readonly string[];
            readonly web_manifest?: {
                readonly [key: string]: unknown;
            };
            readonly artifact_spec?: {
                readonly [key: string]: unknown;
            } | null;
        };
        /** EventOut */
        readonly EventOut: {
            readonly id: number;
            readonly type: string;
            readonly entity_type: string;
            readonly entity_id?: string | null;
            readonly run_id?: string | null;
            readonly data?: {
                readonly [key: string]: unknown;
            };
            /** Format: date-time */
            readonly created_at: string;
        };
        /** ExecutorOut */
        readonly ExecutorOut: {
            readonly key: string;
            readonly label: string;
            readonly handler_kind: string;
            readonly scope: string;
            readonly skill?: string | null;
            readonly selectors?: {
                readonly [key: string]: unknown;
            };
        };
        /** ItemArtifactSlotOut */
        readonly ItemArtifactSlotOut: {
            readonly slot: components["schemas"]["ArtifactSlotOut"];
            readonly ref?: components["schemas"]["ArtifactRefOut"] | null;
            /** @default false */
            readonly undeclared: boolean;
        };
        /** ItemArtifactsOut */
        readonly ItemArtifactsOut: {
            readonly run_id: string;
            readonly item_id: string;
            readonly spec?: components["schemas"]["ArtifactSpecOut"] | null;
            readonly slots?: readonly components["schemas"]["ItemArtifactSlotOut"][];
        };
        /** LedgerItemOut */
        readonly LedgerItemOut: {
            readonly id: number;
            readonly project_id: string;
            readonly item_id: string;
            readonly seq: number;
            /** @default  */
            readonly title: string;
            readonly payload?: {
                readonly [key: string]: unknown;
            };
            /** @default unseen */
            readonly status: string;
            readonly first_seen_run?: string | null;
            readonly resolved_run?: string | null;
        };
        /** LedgerRefreshResult */
        readonly LedgerRefreshResult: {
            readonly project_id: string;
            readonly domain_id: string;
            readonly items_upserted: number;
            readonly milestones_upserted: number;
        };
        /** ManagedProcessOut */
        readonly ManagedProcessOut: {
            readonly path: string;
            readonly port: number;
            readonly pid?: number | null;
            readonly status: string;
            readonly session_id?: string | null;
            readonly started_at?: string | null;
            readonly last_error?: string | null;
            readonly key?: string | null;
        };
        /** MilestoneOut */
        readonly MilestoneOut: {
            readonly id: number;
            readonly project_id: string;
            readonly name: string;
            readonly boundary_item_id?: string | null;
            /** @default open */
            readonly status: string;
        };
        /** NodeRunOut */
        readonly NodeRunOut: {
            readonly id: string;
            readonly run_id: string;
            readonly node_key: string;
            readonly node_type: string;
            readonly status: string;
            /** @default 100 */
            readonly priority: number;
            readonly dependencies?: readonly string[];
            readonly result?: {
                readonly [key: string]: unknown;
            } | null;
            readonly error?: {
                readonly [key: string]: unknown;
            } | null;
            readonly shard_id?: string | null;
            readonly started_at?: string | null;
            readonly finished_at?: string | null;
        };
        /** PipelineNode */
        readonly PipelineNode: {
            readonly id: string;
            readonly node_key: string;
            readonly node_type: string;
            readonly scope: string;
            readonly status: string;
            readonly shard_id?: string | null;
            readonly shard_index?: number | null;
            readonly dependencies?: readonly string[];
            /** @default 100 */
            readonly priority: number;
        };
        /** PipelineOut */
        readonly PipelineOut: {
            readonly run_id: string;
            readonly template_id: string;
            readonly status: string;
            readonly shards?: readonly components["schemas"]["ShardOut"][];
            readonly nodes?: readonly components["schemas"]["PipelineNode"][];
            /** @default 0 */
            readonly completed: number;
            /** @default 0 */
            readonly failed: number;
            /** @default 0 */
            readonly skipped: number;
        };
        /** PlanOut */
        readonly PlanOut: {
            readonly project_id: string;
            readonly snapshot?: {
                readonly [key: string]: unknown;
            };
            readonly suggestions?: readonly {
                readonly [key: string]: unknown;
            }[];
            /** Format: date-time */
            readonly refreshed_at: string;
        };
        /** PlanSnapshot */
        readonly PlanSnapshot: {
            readonly project_id: string;
            readonly total_items: number;
            readonly by_status?: {
                readonly [key: string]: number;
            };
            readonly milestones?: readonly components["schemas"]["MilestoneOut"][];
            readonly suggestions?: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly latest_plan?: components["schemas"]["PlanOut"] | null;
        };
        /** RunCreate */
        readonly RunCreate: {
            readonly domain_id: string;
            readonly template_id?: string | null;
            /** @default  */
            readonly items_dir: string;
            /** @default 3 */
            readonly shards: number;
            /** @default mock */
            readonly backend: string;
            /** @default  */
            readonly base_ref: string;
            readonly config?: {
                readonly [key: string]: unknown;
            };
        };
        /** RunOut */
        readonly RunOut: {
            readonly id: string;
            readonly domain_id: string;
            readonly template_id: string;
            readonly status: string;
            readonly items?: readonly {
                readonly [key: string]: unknown;
            }[];
            /** @default  */
            readonly state_root_rel: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly started_at?: string | null;
            readonly finished_at?: string | null;
        };
        /** RunResult */
        readonly RunResult: {
            readonly run_id: string;
            readonly status: string;
            readonly completed: number;
            readonly failed: number;
            readonly skipped: number;
            readonly state_root_rel: string;
        };
        /** ShardOut */
        readonly ShardOut: {
            readonly id: string;
            readonly run_id: string;
            readonly index_num: number;
            readonly status: string;
            readonly items?: readonly string[];
            /** @default  */
            readonly base_ref: string;
        };
        /** StateIndexEntry */
        readonly StateIndexEntry: {
            readonly kind: string;
            readonly path: string;
            readonly layer: string;
            readonly scope: string;
            /** @default  */
            readonly node_run_id: string;
            /** @default  */
            readonly shard_id: string;
            /** @default  */
            readonly item_id: string;
            /** @default 0 */
            readonly attempt: number;
            /** @default  */
            readonly slot: string;
            /** @default 0 */
            readonly size: number;
            /** @default  */
            readonly sha256: string;
            /** @default  */
            readonly written_at: string;
        };
        /** StateObjectOut */
        readonly StateObjectOut: {
            readonly key: {
                readonly [key: string]: unknown;
            };
            readonly kind: string;
            readonly path_rel: string;
            readonly body?: {
                readonly [key: string]: unknown;
            } | null;
        };
        /** TemplateOut */
        readonly TemplateOut: {
            readonly id: string;
            readonly domain_id: string;
            readonly nodes: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly edges: readonly {
                readonly [key: string]: unknown;
            }[];
            /** @default 1 */
            readonly version: number;
            /** @default false */
            readonly is_default: boolean;
            /** @default  */
            readonly fingerprint: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    readonly ApiV1DomainsListDomains: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["DomainOut"][];
                };
            };
        };
    };
    readonly ApiV1ExecutorsListExecutors: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["ExecutorOut"][];
                };
            };
        };
    };
    readonly ApiV1TemplatesListTemplates: {
        readonly parameters: {
            readonly query?: {
                readonly domain?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["TemplateOut"][];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1RunsListRuns: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["RunOut"][];
                };
            };
        };
    };
    readonly ApiV1RunsCreateRun: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["RunCreate"];
            };
        };
        readonly responses: {
            /** @description Document created, URL follows */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1RunsRunIdEventsGetEvents: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly run_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["EventOut"][];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1RunsRunIdPipelineGetPipeline: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly run_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PipelineOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1RunsRunIdGetRun: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly run_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1NodesNodeRunIdGetNode: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly node_run_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["NodeRunOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1NodesNodeRunIdAttemptsListAttempts: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly node_run_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["AttemptOut"][];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1RunsRunIdItemsItemIdArtifactsSlotGetItemArtifactBytes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly run_id: string;
                readonly item_id: string;
                readonly slot: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1RunsRunIdItemsItemIdArtifactsGetItemArtifacts: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly run_id: string;
                readonly item_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ItemArtifactsOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1RunsRunIdStateGetStateIndex: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly run_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["StateIndexEntry"][];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1RunsRunIdStateObjectGetStateObject: {
        readonly parameters: {
            readonly query: {
                readonly layer: string;
                readonly node_run_id?: string | null;
                readonly shard_id?: string | null;
                readonly attempt?: number | null;
                readonly slot?: string | null;
            };
            readonly header?: never;
            readonly path: {
                readonly run_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StateObjectOut"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1AttemptsAttemptIdTranscriptGetTranscript: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly attempt_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly {
                        readonly [key: string]: unknown;
                    }[];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1AttemptsAttemptIdStreamStreamAttempt: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly attempt_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1EventsStreamStreamGlobal: {
        readonly parameters: {
            readonly query?: {
                readonly catch_up_only?: number;
            };
            readonly header?: {
                readonly "Last-Event-ID"?: string | null;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1RunsRunIdEventsStreamStreamRun: {
        readonly parameters: {
            readonly query?: {
                readonly catch_up_only?: number;
            };
            readonly header?: {
                readonly "Last-Event-ID"?: string | null;
            };
            readonly path: {
                readonly run_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1ProjectsProjectIdPlanGetPlan: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly project_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PlanSnapshot"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1ProjectsProjectIdLedgerListLedger: {
        readonly parameters: {
            readonly query?: {
                readonly status?: string | null;
                readonly limit?: number;
                readonly offset?: number;
            };
            readonly header?: never;
            readonly path: {
                readonly project_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["LedgerItemOut"][];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1ProjectsProjectIdLedgerRefreshRefreshLedger: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly project_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly [key: string]: unknown;
                };
            };
        };
        readonly responses: {
            /** @description Document created, URL follows */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["LedgerRefreshResult"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
    readonly ApiV1AgentsProcessesListProcesses: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["ManagedProcessOut"][];
                };
            };
        };
    };
    readonly ApiV1AgentsProcessesStatusStatusText: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Request fulfilled, document follows */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly ApiV1AgentsProcessesStopAllStopAll: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Document created, URL follows */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: number;
                    };
                };
            };
        };
    };
    readonly ApiV1AgentsProcessesKeyStopStopProcess: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly key: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Document created, URL follows */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
            /** @description Bad request syntax or unsupported method */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly status_code: number;
                        readonly detail: string;
                        readonly extra?: null | {
                            readonly [key: string]: unknown;
                        } | readonly unknown[];
                    };
                };
            };
        };
    };
}
