"""Quality gate entry points for Dagger.

Run via `uv run python -m dagger_check <gate>` or via the nox sessions in pyproject.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def _run(cmd: list[str]) -> int:
    print(f"$ {' '.join(cmd)}")
    return subprocess.call(cmd, cwd=REPO_ROOT)


def ruff() -> int:
    return _run([sys.executable, "-m", "ruff", "check", "."])


def format_check() -> int:
    return _run([sys.executable, "-m", "ruff", "format", "--check", "."])


def mypy() -> int:
    return _run([sys.executable, "-m", "mypy", "packages/dagger_kernel/src"])


def tests() -> int:
    return _run([sys.executable, "-m", "pytest", "packages", "domains", "server", "-q"])


def importlinter() -> int:
    return _run([str(REPO_ROOT / ".venv" / "Scripts" / "lint-imports.exe")])


def _load_domain_schemas() -> None:
    """Best-effort import of each local domain's `schemas` module.

    Domain schema modules register their kinds into SCHEMA_REGISTRY at import
    time, so importing them here makes the generated contract doc cover domain
    kinds alongside the kernel's (novel_digest acceptance Step 1).
    """
    import importlib

    domains_dir = REPO_ROOT / "domains"
    if not domains_dir.exists():
        return
    for domain_dir in sorted(domains_dir.iterdir()):
        src = domain_dir / "src"
        if not src.is_dir():
            continue
        for pkg in sorted(p for p in src.iterdir() if (p / "__init__.py").exists()):
            try:
                if str(src) not in sys.path:
                    sys.path.insert(0, str(src))
                importlib.import_module(f"{pkg.name}.schemas")
            except ModuleNotFoundError:
                continue  # domain has no schemas module — fine
            except Exception as exc:
                print(f"warning: failed to load schemas from {pkg.name!r}: {exc}")


def contracts() -> int:
    # T1.10: regenerate doc/contracts/state_objects.md from the schema registry.
    sys.path.insert(0, str(REPO_ROOT / "packages/dagger_kernel/src"))
    from dagger_kernel.state.schema import SCHEMA_REGISTRY  # type: ignore[import-not-found]

    _load_domain_schemas()
    out_path = REPO_ROOT / "doc" / "contracts" / "state_objects.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# State objects contract",
        "",
        "> AUTO-GENERATED by `python -m dagger_check contracts`. Do not edit by hand.",
        "> Source of truth: `dagger_kernel/state/schemas.py` + `<domain>/schemas/`.",
        "",
        "| kind | version | description |",
        "|------|---------|-------------|",
    ]
    for entry in sorted(SCHEMA_REGISTRY.all(), key=lambda e: e.kind):
        title = entry.schema.get("title", entry.kind)
        lines.append(f"| `{entry.kind}` | v{entry.version} | {title} |")
    lines.extend(["", "## JSON Schemas", ""])
    for entry in sorted(SCHEMA_REGISTRY.all(), key=lambda e: e.kind):
        lines.append(f"### `{entry.kind}` (v{entry.version})")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(entry.schema, indent=2, ensure_ascii=False, sort_keys=True))
        lines.append("```")
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_path.relative_to(REPO_ROOT)}")
    return 0


GATES = {
    "ruff": ruff,
    "format": format_check,
    "mypy": mypy,
    "tests": tests,
    "importlinter": importlinter,
    "contracts": contracts,
}


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: python -m dagger_check <gate>  (one of: " + ", ".join(GATES) + ")")
        return 2
    gate = sys.argv[1]
    if gate == "all":
        rc = 0
        for name, fn in GATES.items():
            print(f"=== {name} ===")
            r = fn()
            if r != 0:
                rc = r
        return rc
    fn = GATES.get(gate)
    if fn is None:
        print(f"unknown gate: {gate!r}; known: {list(GATES)}")
        return 2
    return fn()


if __name__ == "__main__":
    raise SystemExit(main())
